### PR TITLE
Refine application output and ADRG updates

### PR DESCRIPTION
**Pull request by rpodcast**
This PR contains the following updates in preparation for the first test transfer with FDA:

* During a recent Shiny for Submissions task force meeting, I led a brief demonstration of the pilot application. Attendees from the FDA expressed concern about the display of p-values when applying the teal filters to input data. The application now obscures the display of p-values anytime the user applies a filter that reduces the data set. Additional footnotes to the affected tables (primary and efficacy) as well as an additional note in the application information page are now present in the application. Here is a small demo:

P-value visibility

The application has been re-deployed on Shinyapps.io: <https://rconsortium.shinyapps.io/submissions-pilot2>

* The KM plot viewing window has been enlarged to 800 pixels, which greatly improves the legibility of the at-risk table metrics below the plot. I experimented with modifying the font size used for the at-risk table by digging into the internals of [`visR::add_risk_table`](https://github.com/openpharma/visR/blob/main/R/add_risktable.R), but for strange reasons the Shiny app will not render the changes. I will submit an issue to the `{visR}` repository with a reproducible example.
* The ADRG has been updated with additional comments (thank you, @lengning & @fb-elong!) The only change I did not incorporate was the `install = TRUE` flag in the `pkglite::unpack()` call based on the following:
     + The goal is to have the `pilot2wrappers` package installed during the `{renv}` restoration process. If we include `install = TRUE`, that will circumvent the `{renv}` procedure and potentially install different versions of the dependency packages used to build the Shiny application.
     + The errors likely occurred due to an outdated package installer of `{pilot2wrappers}` within the `renv/cellar` directory, which was built with a DESCRIPTION file missing key dependencies (such as `{teal.data}`),  as well as missing the key function `set_data_path`. After correcting these issues, I tested the procedure for installing and executing the application in a completely fresh Windows 11 virtual machine, and the application was un-packed and executed with no issues. I will also try on a fresh Mac OS X VM and RStudio Cloud for completeness.

### CODE REVIEW

**Comment by elong0527** [comment]
Thanks a lot Eric!

**Comment by fb-elong** [comment]
Could you double check the comments in the attached `cover letter` and `adrg` file of the feedback below? 

https://github.com/RConsortium/submissions-pilot2/issues/46#issuecomment-1264453950

It seems some comments are still not resolved. (e.g. mismatch R version 4.1.2 vs. 4.2.0) , missing pkglite package etc)

**Comment by lengning** [comment]
similar comment - seems the `install = TRUE` was not incorporated in the `unpack()` call

thanks @rpodcast !!

**Comment by lengning** [comment]
& bump `pilot2wrappers` version in adrg to 0.5.0? (section 7.4)

**Pull request merged**
